import type {
  AiDocument,
  AiExtraction,
  AiInvoice,
  AiAction,
  AiAgentPerformance,
} from "./types";

export const CABINET = {
  id: "cab-01",
  name: "Fiduciaire Morand & Associés",
  ville: "Lausanne",
  email: "docs@morand.lxstudio.ch",
  plan_comptes: [
    { code: "1020", label: "Compte courant bancaire" },
    { code: "1100", label: "Créances clients (débiteurs)" },
    { code: "1170", label: "TVA récupérable (impôt préalable)" },
    { code: "2000", label: "Dettes fournisseurs (créanciers)" },
    { code: "2200", label: "TVA due" },
    { code: "3200", label: "Produits des ventes" },
    { code: "4000", label: "Charges de marchandises" },
    { code: "4400", label: "Frais de télécommunication" },
    { code: "5000", label: "Salaires" },
    { code: "6000", label: "Loyer et charges" },
    { code: "6200", label: "Frais de véhicule" },
    { code: "6500", label: "Frais de bureau et administration" },
    { code: "6940", label: "Frais bancaires" },
  ],
};

const clientId = CABINET.id;
const now = new Date();
const iso = (daysAgo: number, hour = 9, min = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
};
const dueDate = (daysFromNow: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
};

export const MOCK_DOCUMENTS: AiDocument[] = [
  {
    id: "doc-001",
    client_id: clientId,
    source_email: "facturation@swisscom.ch",
    subject: "Facture Swisscom — Mars 2026",
    body_preview: "Veuillez trouver ci-joint votre facture mensuelle pour l'abonnement professionnel. Montant dû : CHF 248.50.",
    category: "facture_fournisseur",
    urgency: "normale",
    attachments: [{ filename: "facture-swisscom-2026-03.pdf", url: "#", type: "application/pdf", size: 124000 }],
    ai_confidence: 0.97,
    status: "traite",
    created_at: iso(0, 8, 12),
  },
  {
    id: "doc-002",
    client_id: clientId,
    source_email: "compta@brico-leman.ch",
    subject: "Facture n°2026-0438 — Matériel chantier Ducommun",
    body_preview: "Bonjour, merci de régler la facture ci-jointe concernant la livraison du 3 avril.",
    category: "facture_fournisseur",
    urgency: "haute",
    attachments: [{ filename: "FACT-2026-0438.pdf", url: "#", type: "application/pdf", size: 342000 }],
    ai_confidence: 0.94,
    status: "nouveau",
    created_at: iso(0, 9, 45),
  },
  {
    id: "doc-003",
    client_id: clientId,
    source_email: "jean.ducommun@ducommun-sa.ch",
    subject: "Note de frais — Déplacement Zurich",
    body_preview: "Hello, mes frais du déplacement de la semaine dernière. Hôtel + restaurant + CFF.",
    category: "note_frais",
    urgency: "basse",
    attachments: [
      { filename: "hotel-zurich.pdf", url: "#", type: "application/pdf", size: 98000 },
      { filename: "ticket-cff.pdf", url: "#", type: "application/pdf", size: 45000 },
    ],
    ai_confidence: 0.88,
    status: "nouveau",
    created_at: iso(0, 10, 15),
  },
  {
    id: "doc-004",
    client_id: clientId,
    source_email: "no-reply@ubs.ch",
    subject: "Relevé bancaire UBS — Mars 2026",
    body_preview: "Votre relevé de compte du 01.03.2026 au 31.03.2026 est disponible.",
    category: "releve_bancaire",
    urgency: "normale",
    attachments: [{ filename: "releve-ubs-2026-03.pdf", url: "#", type: "application/pdf", size: 187000 }],
    ai_confidence: 0.99,
    status: "valide",
    created_at: iso(1, 7, 30),
  },
  {
    id: "doc-005",
    client_id: clientId,
    source_email: "afc@estv.admin.ch",
    subject: "Décompte TVA — 1er trimestre 2026",
    body_preview: "Décompte TVA trimestriel à soumettre avant le 30 avril 2026.",
    category: "document_fiscal",
    urgency: "haute",
    attachments: [{ filename: "decompte-tva-q1-2026.pdf", url: "#", type: "application/pdf", size: 56000 }],
    ai_confidence: 0.96,
    status: "nouveau",
    created_at: iso(1, 14, 22),
  },
  {
    id: "doc-006",
    client_id: clientId,
    source_email: "marie.favre@favre-electricite.ch",
    subject: "Question sur la clôture fiscale 2025",
    body_preview: "Bonjour, j'aurais besoin de clarifications sur les amortissements à passer avant la clôture.",
    category: "courrier",
    urgency: "normale",
    attachments: [],
    ai_confidence: 0.91,
    status: "traite",
    created_at: iso(2, 11, 5),
  },
  {
    id: "doc-007",
    client_id: clientId,
    source_email: "promotions@marketing-mail.com",
    subject: "🔥 Offre exclusive outils compta -70%",
    body_preview: "Profitez de nos tarifs spéciaux pour les cabinets comptables...",
    category: "spam",
    urgency: "basse",
    attachments: [],
    ai_confidence: 0.99,
    status: "rejete",
    created_at: iso(2, 16, 44),
  },
  {
    id: "doc-008",
    client_id: clientId,
    source_email: "comptabilite@romande-energie.ch",
    subject: "Facture électricité — atelier Chailly",
    body_preview: "Facture n° RE-2026-88421, montant CHF 1'847.25, échéance 25.04.2026.",
    category: "facture_fournisseur",
    urgency: "normale",
    attachments: [{ filename: "RE-2026-88421.pdf", url: "#", type: "application/pdf", size: 156000 }],
    ai_confidence: 0.95,
    status: "traite",
    created_at: iso(3, 9, 18),
  },
  {
    id: "doc-009",
    client_id: clientId,
    source_email: "admin@bouygues-geneve.ch",
    subject: "Rappel facture impayée 2026-0118",
    body_preview: "Deuxième rappel concernant la facture du 12 février 2026, montant CHF 12'450.",
    category: "courrier",
    urgency: "haute",
    attachments: [{ filename: "rappel-2026-0118.pdf", url: "#", type: "application/pdf", size: 78000 }],
    ai_confidence: 0.93,
    status: "nouveau",
    created_at: iso(3, 13, 52),
  },
  {
    id: "doc-010",
    client_id: clientId,
    source_email: "compta@migros.ch",
    subject: "Factures avril — lot mensuel",
    body_preview: "Vos factures de fournitures d'avril (x3) sont groupées dans ce message.",
    category: "facture_fournisseur",
    urgency: "normale",
    attachments: [
      { filename: "migros-2026-04-01.pdf", url: "#", type: "application/pdf", size: 89000 },
      { filename: "migros-2026-04-02.pdf", url: "#", type: "application/pdf", size: 92000 },
      { filename: "migros-2026-04-03.pdf", url: "#", type: "application/pdf", size: 78000 },
    ],
    ai_confidence: 0.9,
    status: "traite",
    created_at: iso(4, 10, 4),
  },
];

export const MOCK_EXTRACTIONS: AiExtraction[] = [
  {
    id: "ext-001",
    document_id: "doc-001",
    client_id: clientId,
    extracted_data: {
      montant: 248.5,
      date: "2026-04-01",
      fournisseur: "Swisscom (Suisse) SA",
      numero_facture: "SC-2026-03-88910",
      tva: 8.1,
      description: "Abonnement professionnel mensuel — Mars 2026",
    },
    suggested_entry: {
      compte_debit: "4400",
      compte_credit: "2000",
      montant: 248.5,
      libelle: "Swisscom — abonnement pro mars 2026",
    },
    status: "en_attente",
    validated_by: null,
    validated_at: null,
    created_at: iso(0, 8, 14),
    ai_confidence: 0.97,
  },
  {
    id: "ext-002",
    document_id: "doc-002",
    client_id: clientId,
    extracted_data: {
      montant: 3845.6,
      date: "2026-04-03",
      fournisseur: "Brico Léman SA",
      numero_facture: "2026-0438",
      tva: 8.1,
      description: "Matériel chantier — Ducommun SA",
    },
    suggested_entry: {
      compte_debit: "4000",
      compte_credit: "2000",
      montant: 3845.6,
      libelle: "Brico Léman — matériel chantier Ducommun",
    },
    status: "en_attente",
    validated_by: null,
    validated_at: null,
    created_at: iso(0, 9, 48),
    ai_confidence: 0.94,
  },
  {
    id: "ext-003",
    document_id: "doc-003",
    client_id: clientId,
    extracted_data: {
      montant: 687.4,
      date: "2026-04-05",
      fournisseur: "Jean Ducommun (note de frais)",
      numero_facture: "NF-2026-14",
      tva: 8.1,
      description: "Déplacement Zurich — hôtel, restaurant, CFF",
    },
    suggested_entry: {
      compte_debit: "6200",
      compte_credit: "1020",
      montant: 687.4,
      libelle: "Note de frais J. Ducommun — Zurich",
    },
    status: "en_attente",
    validated_by: null,
    validated_at: null,
    created_at: iso(0, 10, 18),
    ai_confidence: 0.88,
  },
  {
    id: "ext-004",
    document_id: "doc-008",
    client_id: clientId,
    extracted_data: {
      montant: 1847.25,
      date: "2026-03-28",
      fournisseur: "Romande Énergie SA",
      numero_facture: "RE-2026-88421",
      tva: 8.1,
      description: "Électricité atelier Chailly — Mars 2026",
    },
    suggested_entry: {
      compte_debit: "6000",
      compte_credit: "2000",
      montant: 1847.25,
      libelle: "Romande Énergie — électricité mars 2026",
    },
    status: "valide",
    validated_by: "morand",
    validated_at: iso(3, 10, 2),
    created_at: iso(3, 9, 20),
    ai_confidence: 0.95,
  },
  {
    id: "ext-005",
    document_id: "doc-010",
    client_id: clientId,
    extracted_data: {
      montant: 534.15,
      date: "2026-04-01",
      fournisseur: "Migros Pro",
      numero_facture: "MIG-2026-04-001",
      tva: 2.6,
      description: "Fournitures bureau — avril",
    },
    suggested_entry: {
      compte_debit: "6500",
      compte_credit: "2000",
      montant: 534.15,
      libelle: "Migros — fournitures bureau avril",
    },
    status: "corrige",
    validated_by: "morand",
    validated_at: iso(4, 11, 30),
    created_at: iso(4, 10, 6),
    ai_confidence: 0.9,
  },
];

export const MOCK_INVOICES: AiInvoice[] = [
  {
    id: "inv-001",
    client_id: clientId,
    invoice_number: "2026-0118",
    client_name: "Bouygues Construction Genève",
    amount: 12450.0,
    due_date: dueDate(-22),
    status: "relancee_2",
    last_reminder_at: iso(8),
    created_at: iso(45),
    next_reminder_preview:
      "Objet: Troisième rappel — Facture 2026-0118\n\nMadame, Monsieur,\n\nMalgré nos précédents rappels des 22 mars et 5 avril, la facture 2026-0118 de CHF 12'450.00 datée du 12 février 2026 demeure impayée.\n\nNous vous prions de procéder au règlement sous 7 jours. À défaut, le dossier sera transmis à notre service contentieux.\n\nCordialement,\nFiduciaire Morand & Associés",
  },
  {
    id: "inv-002",
    client_id: clientId,
    invoice_number: "2026-0204",
    client_name: "Ducommun SA",
    amount: 8920.5,
    due_date: dueDate(-9),
    status: "relancee_1",
    last_reminder_at: iso(2),
    created_at: iso(32),
    next_reminder_preview:
      "Objet: Deuxième rappel — Facture 2026-0204\n\nBonjour Monsieur Ducommun,\n\nPour faire suite à notre premier rappel, la facture 2026-0204 d'un montant de CHF 8'920.50 reste en souffrance depuis le 5 avril 2026.\n\nMerci de régulariser rapidement cette situation.\n\nBien à vous,\nFiduciaire Morand & Associés",
  },
  {
    id: "inv-003",
    client_id: clientId,
    invoice_number: "2026-0231",
    client_name: "Favre Électricité Sàrl",
    amount: 4560.8,
    due_date: dueDate(-3),
    status: "en_attente",
    last_reminder_at: null,
    created_at: iso(28),
    next_reminder_preview:
      "Objet: Rappel — Facture 2026-0231\n\nBonjour Madame Favre,\n\nSauf erreur de notre part, la facture 2026-0231 d'un montant de CHF 4'560.80 échue le 11 avril 2026 ne nous est pas encore parvenue.\n\nPourriez-vous procéder au règlement ou nous indiquer la date de paiement prévue ?\n\nCordialement,\nFiduciaire Morand & Associés",
  },
  {
    id: "inv-004",
    client_id: clientId,
    invoice_number: "2026-0245",
    client_name: "Atelier Vaudois SA",
    amount: 15780.0,
    due_date: dueDate(-58),
    status: "relancee_3",
    last_reminder_at: iso(12),
    created_at: iso(78),
    next_reminder_preview:
      "Objet: Mise en demeure — Facture 2026-0245\n\nMadame, Monsieur,\n\nEn dépit de trois rappels et de multiples tentatives de contact, la facture 2026-0245 de CHF 15'780.00 demeure impayée depuis plus de 58 jours.\n\nÀ défaut de règlement intégral sous 10 jours, votre dossier sera transmis à notre service contentieux, sans nouvel avis.\n\nFiduciaire Morand & Associés",
  },
  {
    id: "inv-005",
    client_id: clientId,
    invoice_number: "2026-0267",
    client_name: "Sanitaires Léman Sàrl",
    amount: 2380.25,
    due_date: dueDate(14),
    status: "en_attente",
    last_reminder_at: null,
    created_at: iso(14),
  },
  {
    id: "inv-006",
    client_id: clientId,
    invoice_number: "2026-0112",
    client_name: "Piscines du Lac SA",
    amount: 6720.0,
    due_date: dueDate(-38),
    status: "contentieux",
    last_reminder_at: iso(25),
    created_at: iso(92),
  },
  {
    id: "inv-007",
    client_id: clientId,
    invoice_number: "2026-0289",
    client_name: "Chauffage Servion SA",
    amount: 3210.5,
    due_date: dueDate(21),
    status: "en_attente",
    last_reminder_at: null,
    created_at: iso(7),
  },
];

export const MOCK_ACTIONS: AiAction[] = [
  {
    id: "act-001",
    client_id: clientId,
    action_type: "triage",
    description: "Email de Brico Léman catégorisé : facture fournisseur (urgence haute)",
    confidence: 0.94,
    status: "auto",
    created_at: iso(0, 9, 45),
  },
  {
    id: "act-002",
    client_id: clientId,
    action_type: "extraction",
    description: "Facture Brico Léman 2026-0438 — montant CHF 3'845.60 extrait",
    confidence: 0.94,
    status: "auto",
    created_at: iso(0, 9, 48),
  },
  {
    id: "act-003",
    client_id: clientId,
    action_type: "triage",
    description: "Décompte TVA Q1 2026 de l'AFC marqué urgence haute (échéance 30.04)",
    confidence: 0.96,
    status: "auto",
    created_at: iso(1, 14, 22),
  },
  {
    id: "act-004",
    client_id: clientId,
    action_type: "relance",
    description: "Relance niveau 2 envoyée à Bouygues Construction Genève (facture 2026-0118)",
    confidence: 0.92,
    status: "auto",
    created_at: iso(8, 8, 0),
  },
  {
    id: "act-005",
    client_id: clientId,
    action_type: "extraction",
    description: "Note de frais J. Ducommun — confiance 88% (revue manuelle suggérée)",
    confidence: 0.88,
    status: "valide",
    created_at: iso(0, 10, 18),
  },
  {
    id: "act-006",
    client_id: clientId,
    action_type: "triage",
    description: "Email marketing-mail.com classé en spam (confiance 99%)",
    confidence: 0.99,
    status: "auto",
    created_at: iso(2, 16, 44),
  },
  {
    id: "act-007",
    client_id: clientId,
    action_type: "rapport",
    description: "Rapport quotidien généré — 8 documents traités, 3 en attente de validation",
    confidence: 1,
    status: "auto",
    created_at: iso(0, 7, 0),
  },
  {
    id: "act-008",
    client_id: clientId,
    action_type: "notification",
    description: "Alerte envoyée : facture Bouygues échue depuis 22 jours (CHF 12'450)",
    confidence: 1,
    status: "auto",
    created_at: iso(0, 8, 30),
  },
];

export const MOCK_PERFORMANCE: AiAgentPerformance[] = [
  {
    id: "perf-001",
    client_id: clientId,
    task_type: "triage",
    total_actions: 1248,
    correct_actions: 1211,
    accuracy: 97.0,
    level: "vert",
    updated_at: iso(0, 7, 0),
  },
  {
    id: "perf-002",
    client_id: clientId,
    task_type: "extraction",
    total_actions: 842,
    correct_actions: 769,
    accuracy: 91.3,
    level: "orange",
    updated_at: iso(0, 7, 0),
  },
  {
    id: "perf-003",
    client_id: clientId,
    task_type: "relance",
    total_actions: 187,
    correct_actions: 182,
    accuracy: 97.3,
    level: "vert",
    updated_at: iso(0, 7, 0),
  },
];

export const MOCK_ACCURACY_HISTORY = [
  { day: "01.04", triage: 89.2, extraction: 82.5, relance: 91.0 },
  { day: "05.04", triage: 91.5, extraction: 84.8, relance: 92.3 },
  { day: "10.04", triage: 93.1, extraction: 86.9, relance: 94.1 },
  { day: "15.04", triage: 94.8, extraction: 88.5, relance: 95.2 },
  { day: "20.04", triage: 95.6, extraction: 89.8, relance: 96.0 },
  { day: "25.04", triage: 96.4, extraction: 90.6, relance: 96.8 },
  { day: "30.04", triage: 97.0, extraction: 91.3, relance: 97.3 },
];

export const MOCK_VOLUME_HISTORY = Array.from({ length: 30 }).map((_, i) => {
  const d = new Date(now);
  d.setDate(d.getDate() - (29 - i));
  const base = 18 + Math.round(Math.sin(i / 3) * 6);
  const weekday = d.getDay();
  const volume = weekday === 0 || weekday === 6 ? Math.round(base * 0.3) : base + Math.round(Math.random() * 8);
  return {
    date: `${d.getDate().toString().padStart(2, "0")}.${(d.getMonth() + 1).toString().padStart(2, "0")}`,
    volume,
  };
});

export const GLOBAL_ACCURACY =
  MOCK_PERFORMANCE.reduce((sum, p) => sum + p.accuracy, 0) /
  MOCK_PERFORMANCE.length;

export const GLOBAL_LEVEL: "rouge" | "orange" | "vert" =
  GLOBAL_ACCURACY >= 95 ? "vert" : GLOBAL_ACCURACY >= 50 ? "orange" : "rouge";
